alias dcr='docker compose run'
alias dce='docker compose exec'
alias dcu='docker compose up'
alias dc='docker compose'
alias dcu='docker compose up'
alias dcd='docker compose down'
alias dps='docker ps'
